### ISSUE TITLE
Java.IO.IOException with Xamarin

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#172] opened 2018-01-20 17:13 UTC
See reported issue from customer with support ticket 2623 below:

```
OnePlus running Android 5.1.1

Stack: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9d2d3880 + 0x00024> in :0 at Java.Interop.JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance,
 Java.Interop.JniMethodInfo method,
 Java.Interop.JniArgumentValue* args) <0x9e00e56c + 0x000ab> in <3633915aa47a49dc9b896d4cd2a10241>:0 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember,
 Java.Interop.IJavaPeerable self,
 Java.Interop.JniArgumentValue* parameters) <0x9e01a078 + 0x00093> in <3633915aa47a49dc9b896d4cd2a10241>:0 at Java.Net.HttpURLConnection.get_ResponseCode () <0x9c73d820 + 0x00053> in <9d04d2eb2c6048a38a7624eb701b1638>:0 at Xamarin.Android.Net.AndroidClientHandler+<>cDisplayClass44_0.b2 () <0x9c55f960 + 0x00023> in <9d04d2eb2c6048a38a7624eb701b1638>:0 at System.Threading.Tasks.Task1[TResult].InnerInvoke () [0x0000f] in <ea1cfdebd134422996e26080581c8a25>:0 at System.Threading.Tasks.Task.Execute () <0x9d26e570 + 0x00053> in <ea1cfdebd134422996e26080581c8a25>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9d2d3880 + 0x00024> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x9d2d60ac + 0x000b7> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x9d2d6014 + 0x0008f> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x9d2d5fbc + 0x0004f> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in :0 at Xamarin.Android.Net.AndroidClientHandler+d44.MoveNext () <0x9c55fa58 + 0x00d9b> in <9d04d2eb2c6048a38a7624eb701b1638>:0 — End of stack trace from previous location where exception was thrown — at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9d2d3880 + 0x00024> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x9d2d60ac + 0x000b7> in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x9d2d6014 + 0x0008f> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x9d2d5fbc + 0x0004f> in :0 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[TResult].GetResult () <0x9d2d6788 + 0x0001b> in <ea1cfdebd134422996e26080581c8a25>:0 at Xamarin.Android.Net.AndroidClientHandler+<SendAsync>d__39.MoveNext () <0x9c55e5f4 + 0x00883> in <9d04d2eb2c6048a38a7624eb701b1638>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9d2d3880 + 0x00024> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x9d2d60ac + 0x000b7> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x9d2d6014 + 0x0008f> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x9d2d5fbc + 0x0004f> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[TResult].GetResult () <0x9d2d6788 + 0x0001b> in :0 at System.Net.Http.HttpClient+d49.MoveNext () <0x9e0339a8 + 0x003b3> in <5aa76de78fda4a7088372a26c45ff836>:0 — End of stack trace from previous location where exception was thrown — at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9d2d3880 + 0x00024> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x9d2d60ac + 0x000b7> in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x9d2d6014 + 0x0008f> in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x9d2d5fbc + 0x0004f> in :0 at System.Runtime.CompilerServices.TaskAwaiter1[TResult].GetResult () <0x9d2d62fc + 0x0001b> in <ea1cfdebd134422996e26080581c8a25>:0 at IO.Ably.AblyHttpClient+<Execute>d__21.MoveNext () <0x9ba6bc14 + 0x00c73> in <762ba4d2da794608b090b081586466af>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9d2d3880 + 0x00024> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x9d2d60ac + 0x000b7> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x9d2d6014 + 0x0008f> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x9d2d5fbc + 0x0004f> in <ea1cfdebd134422996e26080581c8a25>:0 at System.Runtime.CompilerServices.TaskAwaiter1[TResult].GetResult () <0x9d2d62fc + 0x0001b> in :0 at IO.Ably.AblyRest+d__35.MoveNext () <0x9ba5bce0 + 0x004b7> in <762ba4d2da794608b090b081586466af>:0 — End of managed Java.IO.IOException stack trace — java.io.EOFException at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95) at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179) at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101) at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628) at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388) at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332) at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500) at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
```

This appears to be a timeout or failed HTTP request, but before we dive into the platform logs, @withakay can you please give us your view on what is happening here?

**Comment by withakay** [comment] 2018-01-20 21:14
I have some questions: 

1) What is the frequency of this error
2) Do you have code deployed on other devices and/or Android versions that does not exhibit this error?
3) Are you setting the HttpClientHandler to use AndroidClientHandler (based on the okhttp error I am guessing you are)?

**Comment by withakay** [comment] 2018-01-22 19:37
I don't think this is a problem with ably-dotnet directly but with [okhttp](https://github.com/square/okhttp) which is used by Xamarin to bind to the native Android HTTP library, hence why you are not seeing similar issues on iOS (Xamarin has a similar option for iOS that binds to NSUrlConnection iirc). Not using AndroidClientHandler may resolve the problem (I have not been able to repeat the issue, so I can't say for sure) at the cost of performance.
@ndastur If you can provide a reproduction that working in the Android emulator I am happy to investigate further.

**Comment by ndastur** [comment] 2018-01-22 21:03
That would make sense and at present only seems to be 5.1.1 which is a notorious android release

**Comment by withakay** [comment] 2018-01-22 21:21
@ndastur are you seeing this on multiple devices running 5.1.1 or just one?

**Comment by ndastur** [comment] 2018-01-22 22:18
Multiple

**Comment by withakay** [comment] 2018-02-01 16:58
@ndastur have you come up with a fix/work around for this problem? Did you try not selecting AndroidClientHandler perhaps?
I don't think there is anything more I can do as this seems to be an upstream problem :(

**Comment by ndastur** [comment] 2018-02-01 17:00
Hi @withakay I haven't been able to investigate yet. But moving from AndroidClientHandler is not really an option due to other reasons. I will try and look again at this next week

**Comment by withakay** [comment] 2018-02-22 20:13
@ndastur Any update on this, or can I close the issue?

**Comment by withakay** [comment] 2018-03-13 13:20
I am closing this due to inactivity.

**Closed by withakay** 2018-03-13 13:20 UTC
