### ISSUE TITLE
Async Subscribe and handlers

### ISSUE THREAD

**Issue by siberianguy** [ably/ably-dotnet#94] opened 2017-02-12 13:46 UTC
It seems like Subscribe process lacks async support in two ways. 

First, there is no async version of Subscribe method.

Second, there's no way to specify async handler for Subscribe. So I can not use await as part of my handler. To fix that, there should be Subscribe overload that takes Func<Message, Task> instead of Action<Message> as argument.

**Comment by mattheworiordan** [comment] 2017-02-13 12:49
Thanks for the feedback @alexidsa, I'll get @marto83 (the maintainer of this live) to provide his thoughts.

**Comment by marto83** [comment] 2017-02-13 13:28
@alexidsa I cannot see a need to have an async version for the Subscribe method. Out of curiosity in what circumstance would you need an async Subscribe method?

I do like the idea of allowing for async handlers to be passed. It shouldn't be a big change. I'll get that added to the list for the next release.

**Comment by alexidsa** [comment] 2017-02-13 13:33
@marto83, well... it all comes down to a question how long does it take to make Subscribe synchronously? Can it block, let's say, WPF application even for a little bit being executed in UI thread? I guess it should take around what Entity Framework's DataContext.SaveChanges method takes and EF provides async overload.

**Comment by marto83** [comment] 2017-02-13 13:45
I see what you mean. The Subscribe method can be run synchronously. All it does is registers a handler internally so next time a message arrives the library will go through all the registered handlers and decide whether they need to be executed or not. It doesn't do any IO.

**Comment by alexidsa** [comment] 2017-02-13 13:50
Hm... Now I'm really confused. I expected it tell the server "next time broadcast to this channel, let me know as I care about this channel now". It is'l like you say, it means all messages are sent by the server to all connected clients both to those which subscribed and those who did not?

**Comment by marto83** [comment] 2017-02-13 14:13
You tell the server that you care about a channel when you create a channel and `Attach` it. The attach operation can be explicit by calling AttachAsync or it can be done implicitly by other operations. 
So when you call `Subscribe` if the channel is not yet attached in the background it will attempt to attach the channel. It does not block the current thread as it is done on a managed thread inside the library. 
Let me know if you have more questions.

**Comment by alexidsa** [comment] 2017-02-13 14:50
Thanks for the explanation, now it all makes sense. So with current implementation when Subscribe call is returned I still can be not subscribed (if background attachment is not done yet). From architecture point of view, it would be better to call AttachAsync as part of subscribe (if it's the first subscribe to this channel, so we're not attached) and that's where we need SubscribeAsync :)

**Comment by marto83** [comment] 2017-02-13 15:06
So if you want to find out whether you have attached to the channel you can subscribe to get `StateChanged` events on the channel itself. I would leave the `Attach` happen in the background. It is one less thing you need to worry about. 
If you want to handle the case where `Attach` fails for some reason you can do that by reacting to a `StateChanged` events.

**Comment by alexidsa** [comment] 2017-02-14 11:24
You're 100% right from implementation point of view. But from library user point of view it looks a little bit different.

Attach seems like an implementation detail that should be hidden inside. I don't see why I would like to call it explicitly. When Subscribe method is returned I expect to be subscribed (physically). When Close method is returned, I expect the server to be already notified about me leaving (based on lack of Async version of Close, I suppose it behaves similarly to Subscribe). For me it just looks confusing and unnatural for .NET ecossystem (I don't remember any similar API).

**Comment by mattheworiordan** [comment] 2017-02-14 15:17
@alexidsa so let me cover off some of this because this is not a .Net issue but simply details on how our API works.

Channels can be attached and not subscribed. There are many reasons for this, including wanting to reserve capacity on a channel for publishing reasons.  If you don't do that, and no one else is attached to a channel, then the channel is only created when you publish to it or subscribe to it, so you are not "reserving capacity" as such and there is a small delay setting up the channel.

Added to this, we are looking at further optimisations later that allow you to have flags on your channel attachment such as "I only want to attach and listen for presence" or "I only want to attach to publish messages" which allows the client library to be optimised by not getting things it is not interested in such as messages published on the channel.

There was a lot of debate about whether `subscribe` should ever implicitly attach because it can be a bit confusing, however we decided that in most cases it was intuitive that if you say you want to subscribe to events on a channel that is initialized but not attached, the you almost certainly want to attach.  However, we need to be clear what subscribe does:

* It implicitly attaches a channel only if it's initialized.  Othewise we assume that if you've explicitly detached it at some point, then you should explicitly reattach it when you want it to be attached.
* It registers a listener for messages on the channel, regardless of whether the implicit attach succeeds or fails.  This is simply because registering a listener has nothing to do with the attach, and if the attach fails the channel could later be re-attached and the listener would still be validly registered to listen for messages when they arrive.

See [RTL7](https://docs.ably.io/client-lib-development-guide/features/#RTL7) of our client library specification for more detail on this, and note that in some client libraries an additional callback can be provided when subscribing that provides feedback to the user on whether the implicit attach succeeded or not.  However, as @marto83 has quite rightly pointed out, it's arguably better for you to simply listen for channel state changes.

**Comment by alexidsa** [comment] 2017-02-17 11:14
First, I'm definitely nitpicking here as the library itself (and ably in general) are great products (I used pubnub before so I have something to compare with). But the way async stuff is implemented in Ably.net does not seem to fit .net ecosystem (based on the Ably documentation, the goal is to create idiomatic API).

When I call DataContext.SaveChanges, I know it's a synchronous method and it's done when the value is returned. Sometimes it does a network trip to save to the database (similar to Attach), sometimes it doesn't as there're no changes and it just returns a completed task (similar to how Subscribe could behave in case we're already subscribed to a channel). That's a very simple and predictable approach. That's how things are done in .NET (at least since async/await support).

When I call Ably methods (i. e. Subscribe, Close, etc.) as a library user I feel confused. There're no Async overloads so I assume they don't do any IO. But then I assume some background process does it. I feel very uncomfortable about it. The recommended callback approach is nice but that's a step back (async/await were introduced to get rid of callbacks).

**Comment by mattheworiordan** [comment] 2017-02-17 11:42
@alexidsa I am not really following you.

Callbacks are provided MOSTLY because it's not a single operation, the callback is called every time that event happens.  So async/await is not relevant.

Subscribe is not a blocking operation, and in a lot of cases, there is nothing to wait for because the channel is already attached for example.  Subscribe is about adding a listener that is called whenever a message / event is received.

The additional callback to Subscribe has nothing to do with the result of Subscribe, it's simply a convenience for people who may want to know the result of the operation.  If we made that an async task, it would imply the operation is blocking which it is not, so that IMHO is far more misleading.

In the case of `Attach`, it is blocking, and therefore we offer two flavours:

* https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Realtime/Channel.cs#L98 because it's consistent with pretty much every other client library API we have
* To make this more .NET idiomatic if you want to use that approach.

I'm loving the feedback and really do appreciate your thoughts, but unfortunately I don't really understand where the issue is at present.

PS. We **aim** to be idiomatic, but not at the cost of the API being needlessly different to other client libs.  Our goal is to have as consistent an API as possible across all languages over being idiomatic, but we do everything we can to marry those two objectives.

**Comment by alexidsa** [comment] 2017-02-17 14:39
As they say in Facebook, code always wins. So let me try to explain my logic using the codebase.

So there's an async version of Attach. It means you assume it can take more than 50ms (general guideline) which is true for any IO. For our discussion it actually doesn't matter what Attach method does. What matters is that it is called as part of Subscribe:

```
if(State != ChannelState.Attached && State != ChannelState.Attaching)
                Attach();

            _handlers.Add(new MessageHandlerAction<Message>(handler));
```

So if Attach itself has an async version, all the public methods that call it also should have async versions. Seems extremely logical to me.

**Comment by mattheworiordan** [comment] 2017-02-17 14:50
>  What matters is that it is called as part of Subscribe:

No, because: 

`await channel.Subscribe(...)`

Always returns in the same loop, there is no activity it waits on.  It's simply a side effect.

Take this for example:

```
man.move() //  this does not require IO, it's sync and is done immediately. The dog barking as a result, is a side-effect
on(man.move) { dog.bark() } // this is a side-effect of the man moving, happens later, but is caused by man moving
```

So to explain further, calling subscribe does two things, registers a listener (no IO, immediate), implicitly moves the channel to the `ATTACHING` state if channel is `INITIALIZED` (no IO, immediate).

Then once the channel moves to the attaching state, the side effect of that is it will send an `ATTACH` request to Ably, but only if the connection is available. If not, it waits until a connection becomes available and then sends it.

So if we exposed `channel.Subscribe` as an Async method, you'd potentially be waiting until a connection becomes available, the authentication occurs, and the channel is attached successfully when what you're asking it to do is register a listener.

**Comment by alexidsa** [comment] 2017-02-17 17:21
I really don't want to take too much of your time on this minor thing but I don't understand you. Why do you mean "returns in the same loop?". Here's a flow I see:

1. Subscribe calls Attach (if not attached)
2. Attach calls SetChannelState(ChannelState.Attaching)
3. SetChannelState calls HandleStateChange
4. HandleStateChange calls Connection.Connect (again, somehow not async) and then calls SendMessage (again, not async).

I've created a little [gist](https://gist.github.com/alexidsa/711ea073818584e2f54d6aad223ae128) to test Subscribe performance. Here're my results (using average WiFi in a hotel in Thailand):

> Subscribing to the first channel for the first time:
> 00:00:00.0287481
> Subscribing to other event of the same channel
> 00:00:00.0000218
> Subscribing to the second channel for the first time
> 00:00:00.0003635

The first subscribe call to a new channel takes 30ms. It could be more or less depending or the circamstances but sounds like something that should be async (including the whole underlying IO stack like Connect, Open, Close, etc.).

**Comment by mattheworiordan** [comment] 2017-02-17 18:21
If the first call is blocking, then that's a bug in the implementation @alexidsa.  It should not, it should change the state which triggers asynchronous events that connect etc.  If that is not the case, then I will raise an issue to get that addressed. 

@marto83 any thoughts on this?  Sounds like the implementation is mistakenly doing sync things?

**Comment by marto83** [comment] 2017-02-19 22:42
@alexidsa thanks for looking through the code. 

Just for some background. The library works over a few threads. I keep the synchronisation context so any callbacks or events happen on the user's thread. It also keeps an internal thread (let's call it the Ably thread) for admin kind of stuff - e.g. state transitioning, message processing, and there is one more thread managed by the WebSockets library. 
So when you call Attach for the first time it will go ahead and call `Connect` if the connection is not established but all that method does is to change the internal state to Connecting and then the actual action is delegated to the Ably thread to complete so the method completes without doing any actual IO. 

If you enable debug logging you will see that all the `Subscribe` calls complete before the Web socket is actually connected. Here is a partial log ( I used the logger sink from https://github.com/ably/ably-dotnet/blob/master/src/Ably.ConsoleUnitTests/MyLogger.cs )

Thread `#1` is the user's thread where thread `#3` is Ably's thread

**> Subscribing to the first channel for the first time:**                                                                          
> 10:27:10.499 #3 xx Connecting: BeforeTransition                                                                           
>     10:27:10.500 #3 Connection notifying subscribers for state change `Connecting`                                            
>     10:27:10.502 #1 #channel-1: Changing state to: 'Attaching'.                                                               
>     10:27:10.502 #3 xx Connecting: Attaching state                                                                            
>     10:27:10.503 #1 Aborting timer '#channel-1 timer'                                                                         
>     10:27:10.504 #1 Setting up timer '#channel-1 timer' to run action after 10 seconds. Autoreset: False                      
>     10:27:10.504 #3 Creating transport                                                                                        
>     10:27:10.506 #1 Current state: Connecting. Sending message: { action=Attach }                                             
>     10:27:10.508 #1 Queuing message with action: Attach. Connection State: Connecting                                         
> 00:00:00.0126814                                                                                                              
**> Subscribed channel 1 event 2**                                                                                                  
**> Subscribing to other event of the same channel**                                                                                
> 00:00:00.0000099                                                                                                              
>     10:27:10.511 #3 Connecting to web socket on url: wss://realtime.ably.io/?key=key&v=0.8&lib=dotn
> et-0.8.4&format=msgpack&echo=true                                                                                             
**> Subscribed channel 1 event 2**                                                                                                  
**> Subscribing to the second channel for the first time**                                                                          
>     10:27:10.512 #1 #channel-2: Changing state to: 'Attaching'.                                                               
>     10:27:10.512 #1 Aborting timer '#channel-2 timer'                                                                         
>     10:27:10.512 #1 Setting up timer '#channel-2 timer' to run action after 10 seconds. Autoreset: False                      
>     10:27:10.512 #1 Current state: Connecting. Sending message: { action=Attach }                                             
>     10:27:10.512 #1 Queuing message with action: Attach. Connection State: Connecting                                         
> 00:00:00.0009971                                                                                                              
**> Subscribed channel 2 event 1**                                                                                                  
>     10:27:10.518 #3 Connecting socket                                                                                         
>     10:27:10.519 #3 Setting up timer 'Connecting state timer' to run action after 10 seconds. Autoreset: False                
>     10:27:11.046 #8 Websocket opened!                                                                                         
>     10:27:11.063 #3 Transport state changed to: Connected.                                                                    
>     10:27:11.205 #8 Websocket data message received. Raw: { "action" : 4, "connectionId" : "L2NvrstUWt", "connectionKey" : "10 ....

The `Subscribe` call even though it has to do a bit more work initially it never blocks for any IO. Even if we create an async version it will return an already completed task it.

Let me know if this makes things clearer. All further questions are welcome.

**Comment by alexidsa** [comment] 2017-02-20 06:17
Thanks, it makes sense and 30ms is not critical enough for UI. The only thing I don't understand is if Attach doesn't do any IO, why did you introduce AttachAsync in the first place?

P. S. Just minor thing I noticed looking through the codebase: file for RealtimeChannel class is named Channel.

**Comment by mattheworiordan** [comment] 2017-02-21 11:52
> The only thing I don't understand is if Attach doesn't do any IO, why did you introduce AttachAsync in the first place?

Because it's perfectly valid to wait until the Attach process is completed i.e. success or failure.  For example, this is a very common pattern:

```
on(attached, (err) => {
  if (err) { return handleFailure() }
  doSomethingNowThatWeAreAttached()
})
```

So when you say there is no IO, there is, it sends a request to Ably to ATTACH and waits for an ACK

**Comment by siberianguy** [comment] 2017-02-21 14:33
Okay, thanks for the explanation!

**Comment by mattheworiordan** [comment] 2017-02-22 02:43
You happy for me to close this @siberianguy or do you think there are any actions from this thread?

**Closed** 2017-02-22 02:54 UTC
