### ISSUE TITLE
Consider setting EchoMessages default to false

### ISSUE THREAD

**Issue by ndastur** [ably/ably-dotnet#123] opened 2017-08-08 23:15 UTC
According to the docs at https://support.ably.io/support/solutions/articles/3000053844-how-does-ably-count-messages- it seems that an echoed message counts and message counts a reflected in the cost of the service. It would seem better and more transparent for users to explicitly set echo to true and accept the "extra" cost.

I am also not sure what function message echoing provides and therefore even less reason for it to be on by default

**Comment by mattheworiordan** [comment] 2017-08-21 12:44
@ndastur apologies for our slow response to this.  I realise this is not really a .NET issue but a general issue, so Martin assumed I would respond.

When you subscribe for messages on a channel, we believe that it's more correct, in a lot of cases, for all messages regardless of publisher to be emitted.  With that design, all subscribers get a consistent stream of messages.  I can certainly see an argument for not wanting the echo though and that's why we offer that.  Saying that, if you build a UI, for example, that consumes events on a channel and uses that to update the UI, you'd have to special case events generated locally versus globally.  Also, you'd then not know if your event happened before another event published on the channel around the same time and as such your assumption around ordering of events would be different to other subscribers on that channel.

I will raise it internally to see what others think about changing the default, however even if we agreed, changing it would be a huge breaking change and I fear would cause a lot of unexpected problems for customers now.

**Comment by ndastur** [comment] 2017-08-22 10:14
Ty @mattheworiordan. I get the idea of messages being emitted regardless of publisher but not sure why the echo back again?? From what I read in the docs there is a success result from the Ably server that guarantees receipt so what does the echo add?
Also in our app I haven't changed the default and I don't believe we get an echo message back. So might be a bit of cross purpose talking happening here??

**Comment by mattheworiordan** [comment] 2017-08-30 13:04
>  From what I read in the docs there is a success result from the Ably server that guarantees receipt so what does the echo add?

It means that subscribers are decoupled from publisher actions, which underpins the Pub/Sub pattern i.e. you could publish via REST, via Realtime, or via another RPC / HTTP call to your servers, and still subscribe in the same way.  Additionally, it means you can guarantee that the order you receive messages is the same order all subscribers receive in that region on that channel.  Without messages echoed, this would not be possible and every subscriber would like end up seeing messages in a different order.

I am closing this issue because we are not going to change the `echoMessages` behaviour for the foreseeable future.

> Also in our app I haven't changed the default and I don't believe we get an echo message back. So might be a bit of cross purpose talking happening here??

You do.  Please raise a separate issue for this if you can reproduce the problem and send us a code example so we can investigate.  This has not been reported before.

**Closed by mattheworiordan** 2017-08-30 13:04 UTC
Labels: question
