### ISSUE TITLE
Socket is null in MsWebSocketTransport

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#264] opened 2018-10-16 19:57 UTC
I get this exception from time to time. It probably happens when there are issues with my internet connectivity.

![socket_is_null](https://user-images.githubusercontent.com/4531542/47043475-65526b80-d196-11e8-8f8f-1c8bca0da1b2.png)

**Comment by mattheworiordan** [comment] 2018-10-16 22:14
Thanks for reporting, sorry to hear @lovetofail.

Can you confirm the version of the lib you are using?  Any other info you can provide such as platform, ways to reproduce (I know you mention connectivity, but can you reproduce?).

**Comment by lovetofail** [comment] 2018-10-17 08:07
Using commit eb4e7d7625fc582ba43993486d60778af19fcbfd. Windows Forms. Framework 4.6.
Sorry, not able to reproduce. 
It sometimes happens when a program is running, computer put to sleep for a night and right after the computer wakes the exception occurs. Or sometimes when I'm in a step by step debug mode for a few minutes.

**Comment by withakay** [comment] 2018-10-17 08:38
@lovetofail 
It would be really helpful if you could capture a debug log, would that be possible?

**Comment by lovetofail** [comment] 2018-10-17 08:52
07:39:34 Entered debugging mode
07:44:13 Resumed and at 07:44:14 there is an error.
[socketNull.log](https://github.com/ably/ably-dotnet/files/2486523/socketNull.log)

**Comment by DaTester** [comment] 2018-10-19 10:06
Just to update on my previous post - i'm afraid we still get error if AutoConnect is false.

**Comment by withakay** [comment] 2019-04-25 11:59
@DaTester this issue should be resolved with the 1.1.1 release. Let us know how you get on?

**Comment by withakay** [comment] 2019-05-10 10:41
Closing due to inactivity

**Closed by withakay** 2019-05-10 10:41 UTC
Labels: bug
