### ISSUE TITLE
Setting UseBinaryProtocol = true prevents client connection

### ISSUE THREAD

**Issue by pseabury** [ably/ably-dotnet#84] opened 2016-09-21 15:53 UTC
If I simply try to connect using the AblyRealtime client with the setting [UseBinaryProtocol = true], the client never transitions from connecting=>connected.  If I set [UseBinaryProtocol = false], the client connects correctly.  The settings class is left out but you can simply replace your key and clientId.

``` C#
        [TestMethod]
        public void TestConnectAndSend()
        {
            var settings = AblySettings.ParseFromConfig(true);
            var pushOptions = new ClientOptions(settings.RootKey) { UseBinaryProtocol = false, Tls = true, AutoConnect = false, ClientId = settings.ClientName };
            AblyRealtime pushClient = new AblyRealtime(pushOptions);
            bool everConnected = false;

            pushClient.Connection.ConnectionStateChanged += (sender, e) =>
            {
                Debug.WriteLine("Ably ConnectionEvent: {0}->{1}", e.Previous, e.Current);
                if (e.Current == IO.Ably.Realtime.ConnectionState.Connected)
                {
                    pushClient.Channels["TestChannel"].Publish("TestEvent", "TestData");
                    Debug.WriteLine("Sent TestEvent.TestData to TestChannel");
                    everConnected = true;
                }
            };
            pushClient.Connect();

            // Wait for Connection to happen 90s ...
            Thread.Sleep(1000 * 90);

            Assert.IsTrue(everConnected);
        }
```

**Comment by mattheworiordan** [comment] 2016-09-21 16:00
Sorry about this @pseabury. We'll take a look shortly although our .NET guy is not here today.

**Comment by marto83** [comment] 2016-09-21 16:16
Hi @pseabury. Can you set the LogLevel to `Debug` at the beginning of the test - `Logger.LogLevel = LogLevel.Debug;`. It will output verbose messages to the Debug window.

**Comment by pseabury** [comment] 2016-09-21 18:15
I made the logging change, but see no additional output in the debug window.

**Comment by marto83** [comment] 2016-09-21 21:29
@pseabury. That's really weird. I can't replicate it locally. 
I haven't tried with MS Test but with XUnit the following test passes. 

            //Rest.Test().Wait();
            var options = new ClientOptions("[key]")
            {
                ClientId = "test",
                Tls = true,
                UseBinaryProtocol = true,

            };
            var client = new AblyRealtime(options);
            var everConnected = false;
            client.Connection.ConnectionStateChanged += (sender, e) =>
            {
                Console.WriteLine("Ably ConnectionEvent: {0}->{1}", e.Previous, e.Current);
                if (e.Current == IO.Ably.Realtime.ConnectionState.Connected)
                {
                    client.Channels["TestChannel"].Publish("TestEvent", "TestData");
                    Console.WriteLine("Sent TestEvent.TestData to TestChannel");
                    everConnected = true;
                }
            };

            client.Connect();

            Thread.Sleep(1000 * 9);
            everConnected.Should().BeTrue();

Do you mind trying the same code in a console app in case MsTest is having problems with the MsgPack serialization?

**Comment by marto83** [comment] 2016-09-21 21:43
I've run the same test under MsTest and it works correctly. Here is the expected output:

```
Ably: [Debug] 09:36:02.127 #7 Protocol set to: MsgPack
Ably: [Debug] 09:36:02.142 #7 Initializing message encodings. json,utf-8,cipher,base64 initialized
Ably: [Info] 09:36:02.174 #7 Using token authentication.
Ably: [Info] 09:36:02.176 #7 Authentication method: Token auth with client-side signing
Ably: [Debug] 09:36:02.211 #8 ConnectionManager thread created
Ably: [Debug] 09:36:02.213 #7 xx Changing state from Initialized => Connecting. SkipAttach = False.
Ably: [Debug] 09:36:02.215 #8 xx Connecting: BeforeTransition
Ably: [Debug] 09:36:02.216 #8 Connection notifying subscribers for state change `Connecting`
Ably: [Debug] 09:36:02.221 #8 xx Connecting: Attaching state 
Ably: [Debug] 09:36:02.222 #8 Creating transport
Ably: [Info] 09:36:02.285 #8 Sending POST request to /keys/Jut4Iw.TfZ5eQ/requestToken
Ably: [Debug] 09:36:02.588 #8 Executing request: /keys/Jut4Iw.TfZ5eQ/requestToken
Ably: [Debug] 09:36:03.186 #8 Response received. Status: Created
Ably: [Debug] 09:36:03.186 #8 Content type: application/x-msgpack
Ably: [Debug] 09:36:03.187 #8 Encoding: utf-8
Ably: [Debug] 09:36:03.187 #8 Raw response (base64):hqV0b2tlbtmISnV0NEl3LkRXa2dONGlHc0w3QWl5YWZsaXF4b1JKMEVMN0k0elNNZ1RvV01YUGtHbzAtdzMzX2FmR0pIVkdmSkdLNUVtX0VmV2htQXpKVFBWZkNtUGRzSTBvSjkyNlpTN0NVUXFzWHJjc3RCaDhUZEVIQnljMnRFRlZRTEoyalZyVHYwVnYwM6drZXlOYW1lrUp1dDRJdy5UZlo1ZVGmaXNzdWVkzwAAAVdOrU8Cp2V4cGlyZXPPAAABV07kPYKqY2FwYWJpbGl0eat7IioiOlsiKiJdfahjbGllbnRJZKR0ZXN0
Ably: [Info] 09:36:03.188 #8 Protocol:MsgPack
Ably: [Debug] 09:36:03.205 #8 Response: { "token" : "Jut4Iw.DWkgN4iGsL7AiyafliqxoRJ0EL7I4zSMgToWMXPkGo0-w33_afGJHVGfJGK5Em_EfWhmAzJTPVfCmPdsI0oJ926ZS7CUQqsXrcstBh8TdEHByc2tEFVQLJ2jVrTv0Vv03", "keyName" : "Jut4Iw.TfZ5eQ", "issued" : 1474493763330, "expires" : 1474497363330, "capability" : "{\"*\":[\"*\"]}", "clientId" : "test" }
Ably: [Debug] 09:36:03.231 #8 Connecting to web socket on url: wss://realtime.ably.io/?accessToken=Jut4Iw.DWkgN4iGsL7AiyafliqxoRJ0EL7I4zSMgToWMXPkGo0-w33_afGJHVGfJGK5Em_EfWhmAzJTPVfCmPdsI0oJ926ZS7CUQqsXrcstBh8TdEHByc2tEFVQLJ2jVrTv0Vv03&v=0.8&format=msgpack&echo=true&clientId=test
Ably: [Debug] 09:36:03.239 #8 Connecting socket
Ably: [Debug] 09:36:03.245 #8 Setting up timer 'Connecting state timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 09:36:03.381 #11 Websocket opened!
Ably: [Debug] 09:36:03.384 #8 Transport state changed to: Connected.
Ably: [Debug] 09:36:03.387 #11 Websocket data message received. Raw: { "action" : 4, "connectionId" : "kwAh_Lk_fG", "connectionKey" : "108a6afb!kwAh_Lk_fGF3KmmF-17d1a7108a6afb", "connectionSerial" : -1, "connectionDetails" : { "clientId" : "test", "connectionKey" : "108a6afb!kwAh_Lk_fGF3KmmF-17d1a7108a6afb", "maxMessageSize" : 16384, "maxInboundRate" : 15, "maxFrameSize" : 262144, "serverId" : "frontend.6514.1.eu-west-1-A.i-42e6a3ce", "connectionStateTtl" : 120000 } }
Ably: [Debug] 09:36:03.402 #8 Aborting timer 'Connecting state timer'
Ably: [Debug] 09:36:03.403 #8 xx Changing state from Connecting => Connected. SkipAttach = False.
Ably: [Debug] 09:36:03.405 #8 Aborting timer 'Connecting state timer'
Ably: [Debug] 09:36:03.405 #8 xx Connected: BeforeTransition
Ably: [Debug] 09:36:03.407 #8 Connection notifying subscribers for state change `Connected`
Ably: [Debug] 09:36:03.414 #8 #TestChannel: Changing state to: 'Attaching'. 
Ably: [Debug] 09:36:03.416 #8 Aborting timer '#TestChannel timer'
Ably: [Debug] 09:36:03.416 #8 Setting up timer '#TestChannel timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 09:36:03.417 #8 Current state: Connected. Sending message: { action=Attach }
Ably: [Debug] 09:36:03.426 #8 #TestChannel:Attaching queuing message
Ably: [Debug] 09:36:03.427 #8 xx Connected: Attaching state 
Ably: [Debug] 09:36:03.453 #13 Websocket data message received. Raw: { "action" : 11, "channel" : "TestChannel", "channelSerial" : "1087c6c725789598:3" }
Ably: [Debug] 09:36:03.455 #8 #TestChannel: Changing state to: 'Attached'. 
Ably: [Debug] 09:36:03.455 #8 Aborting timer '#TestChannel timer'
Ably: [Debug] 09:36:03.456 #8 Current state: Connected. Sending message: { action=Message, mesasages=[ { name="TestEvent", data=TestData} ] }
Ably: [Debug] 09:36:03.491 #13 Websocket data message received. Raw: { "action" : 15, "id" : "kwAh_Lk_fG-0", "count" : 17, "channel" : "TestChannel", "channelSerial" : "1087c6c725789598:4", "connectionId" : "kwAh_Lk_fG", "connectionSerial" : 0, "timestamp" : 1474493763676, "messages" : [ { "name" : "TestEvent", "clientId" : "test", "data" : "TestData" } ] }
Ably: [Debug] 09:36:03.492 #11 Websocket data message received. Raw: { "action" : 1, "count" : 1, "msgSerial" : 0 }
```

I get it when I debug the test. 

It is just odd that it doesn't work with the binary protocal but works with json. Can you give me more details about your setup? 
What version of Visual studio? 
What is the .net framework version you are using?

**Comment by pseabury** [comment] 2016-09-21 21:57
Originally I wrote this test case because my application code (ASP.NET MVC/WebApi 4.5.2) wasn't connecting.  In the same solution I created a test project and wrote the test code above, with the same result - no connection with binary enabled.

I just created a completely new solution with a console application, and the connection does indeed work.  Any ideas about using this setup in a web project, or why it may behave differently there?

Best,

Paul

**Comment by marto83** [comment] 2016-09-21 22:04
I see. I'll create a .net MVC app tomorrow and give it a try. 

Do you mind me asking how you are using the Realtime library in an MVC application? Do you keep it running in the backgroud to receive messages?

**Comment by pseabury** [comment] 2016-09-21 22:12
Use the .NET realtime client to push application events to the browser via javascript.  Similar to Signal-R but hopefully better supported, easier to use, more scalable.  I do it this way because I want the server side to be the authority for timestamps, transactional behavior etc.

Basically pub/sub to push change events to all of the connected clients.  With Signal-R this was complicated by the pubSub service running on the hosted infrastructure so that when you scaled out, you had to [stand up a backplane](http://www.asp.net/signalr/overview/performance/scaleout-in-signalr) to replicate all of the messages/subscriptions/etc across all nodes.  Basically with SignalR you have to halfway roll your own platform.

**Comment by marto83** [comment] 2016-09-22 08:47
I wonder if it is something to do with the default .Net MVC Synchronization context. 
Can you try and set `CaptureCurrentSynchronizationContext` option to `false`? 

Usually the Rest client is a better fit for web applications. It supports async and sync actions and you can batch send messages. Unless you need to receive messages Rest works better.

**Comment by pseabury** [comment] 2016-09-22 13:44
I've been poking around a bit at your suggestion, but honestly not sure how/where to modify the SyncContext.  
```
HttpContext.Current.?
Request.GetSynchronizationContext().?
```

**Comment by marto83** [comment] 2016-09-22 16:57
Do you mind sharing the code where you init the Realtime library?

**Comment by pseabury** [comment] 2016-09-22 17:12
It's just above in my first post in this thread.

**Comment by marto83** [comment] 2016-09-23 09:25
@pseabury.

Please find the attached Web project which has an MVC site with Ably sending messages on Home controller and getting the history on the About Controller. 

I also had to disable the CaptureCurrentSynchronizationContext. I initialise the library on application start. 

If that doesn't help can you create a sample project where I can replicate the exact issues you are having. 
[AblyTest.zip](https://github.com/ably/ably-dotnet/files/489267/AblyTest.zip)

**Comment by pseabury** [comment] 2016-09-23 14:04
First off, thanks for taking the time to work through this with me.

I traced the issue in my Solutions to the fact that I updated the MsgPack.Cli package to 0.8.0, which indicates as compatible.  If I back off to v0.6.8 of that package, I can use binary protocol and the client doesn't feeeze up.  If I use version 0.8.0, then even with CaptureCurrentSynchronizationContext = false doesn't help.  This is repeatable in the test project you sent - just update the MsgPack.Cli pacakge to the latest stable (0.8.0).

That leads to my 2nd question - based [on the code for AblyRealTime](https://github.com/ably/ably-dotnet/blob/b9e4c355ac487e187a6e49879f0c7760677edc1b/src/IO.Ably.Shared/AblyRealtime.cs), if you don't set a custom SyncContext, and you tell it not to capture the current SyncContext, then it uses no SyncContext at all - is that correct?  I'd need to think about it a bit more, and test it, but potentially that could cause real issues depending on the hosting environment of the ASP.Net stack, right?  Any guidance on this issue?

Paul

**Comment by marto83** [comment] 2016-09-23 16:24
Paul, 

Good find about the MsgPack.Cli. The next version 0.8.4 uses the latest update of MsgPack. It should be out in the next couple of weeks

Regarding SyncContext it is mainly used when you have a UI thread and all the components on the UI thread can only be updated on that thread. So the library tries to be helpful and makes sure it calls the events and callbacks on the thread that initiated it. 
If you don't set a SyncContext then the callback will be called on the internal thread the library keeps. 

I don't think that will be a problem for an MVC application. Do you receive messages as well on the MVC app?

**Comment by pseabury** [comment] 2016-09-23 16:31
No, so far I just send.

Thanks Martin!

**Comment by marto83** [comment] 2016-09-23 16:43
Cool. If you don't plant to use it for receiving I would use the AblyRest
class. It will make things much easier to use and test.

**Comment by mattheworiordan** [comment] 2016-09-25 20:57
@pseabury just checking in to make sure you're happy with things and it's all working OK?

**Comment by pseabury** [comment] 2016-09-25 21:59
Yes thanks for checking.  I just backed out the latest version of the dependency and all is working.  I will likely switch to the REST client soon.

Paul M. Seabury




On Sun, Sep 25, 2016 at 3:57 PM -0500, "mattheworiordan" <notifications@github.com> wrote:












@pseabury just checking in to make sure you're happy with things and it's all working OK?

**Comment by mattheworiordan** [comment] 2016-10-04 21:13
@marto83 is UseBinaryProtocol set to false by default?  It should be true by default, see http://docs.ably.io/client-lib-development-guide/features/#RSC8a

**Comment by mattheworiordan** [comment] 2016-10-05 10:26
@marto83 unfortunately this issue is not fixed I believe.  This from a user today:

> So the connect is definitely working with UseBinaryProtocol = false and not working when set to true.
> I'm using the following versions of the libraries:
> 
> Xamarin.iOS 10.0.1.9 (Android not tested yet)
> Ably Client 0.8.3
> MsgPack.Cli 0.8.0 (also tried 0.9.0-beta1 with no difference)
> Newtonsoft.Json 9.0.1
> Nito.AsyncEx 3.0.1
> WebSocket4Net 0.14.1
> 
> Hope that helps a bit.

**Comment by marto83** [comment] 2016-10-05 10:41
The issue is in MsgPack version 0.8. You need to use v0.6.8 for version
0.8.3 of Ably.

Version 0.8.4 is ready but I need to make sure all the tests pass
everytime. Expect a release by Friday.

M

**Comment by mattheworiordan** [comment] 2016-10-18 16:56
@marto83 was this released?

**Comment by marto83** [comment] 2017-05-01 16:19
the change is released. Closing...

**Closed by marto83** 2017-05-01 16:19 UTC
Labels: bug
