### ISSUE TITLE
Channel fails after token expiration.

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#67] opened 2016-06-13 14:28 UTC
Using latest commit. Token ttl 11min. Sometimes token reauth fails and then Channel and Connection are set to Failed set. I attached a log, maybe you can explain what is up. 
This happens only sometimes. Can you advise on how to reattach to a channel in this case?
The code is basic realtime.Connect(); channel.Attach();
```
==========Items connection: Connecting, Thread:16 Serial:54
Ably: [Debug] 02:02:39.942 #16 xx Connecting: Attaching state 
Ably: [Debug] 02:02:39.943 #16 Creating transport
Ably: [Info] 02:02:39.944 #16 Sending GET request to https://mywebsite.com/ubft.php?hwid=nKWyBjoFxgd0lswgs%2BLWfVvR1Ho%3D&ttl=660&cb=85216
Ably: [Debug] 02:02:39.944 #16 Executing request: https://mywebsite.com/ubft.php?hwid=nKWyBjoFxgd0lswgs%2BLWfVvR1Ho%3D&ttl=660&cb=85216
Ably: [Debug] 02:02:41.410 #16 Connecting to web socket on url: wss://realtime.ably.io/?accessToken=rhSsEA.HzdMPzUAOTvOTk6WvPZFRvFT9wJk8H0NHM3d9-ahiCfLTIk1JZIT2YmulE76CXNwp5yAZQjrdUyC48OGuOV2p8z6yd_EJPDozYC-w69ICYicEMSmB2wGfnuNQ9QCwg8Cfk5BPJe-2fepTORAufll1qAWNeqog5HGjY0k5Ugq5XaFSt9Se1kK80sTOf6ih8R-qzKlzxxhaAyg8wA8kFyQGGw&v=0.8&format=msgpack&echo=true&resume=e7d34afc!IzbrpxbS544xdboL-82955e7d34afc&connection_serial=54
Ably: [Debug] 02:02:41.411 #16 Connecting socket
Ably: [Debug] 02:02:41.412 #16 Setting up timer 'Connecting state timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 02:02:42.309 #31 Websocket opened!
Ably: [Debug] 02:02:42.310 #16 Transport state changed to: Connected.
Ably: [Debug] 02:02:42.310 #31 Websocket data message received. Raw: ��action�channel�ubfp:presence
Ably: [Debug] 02:02:42.332 #31 Websocket data message received. Raw: ��action�connectionId�IzbrpxbS54�connectionKey�'e7dfb66c!IzbrpxbS544xdboL-83acee7dfb66c�connectionSerial6�connectionDetails��clientId�nKWyBjoFxgd0lswgs+LWfVvR1Ho=�connectionKey�'e7dfb66c!IzbrpxbS544xdboL-83acee7dfb66c�maxMessageSize�@Ably: [Debug] 02:02:42.334 #16 Aborting timer 'Connecting state timer'
Ably: [Debug] 02:02:42.356 #16 xx Changing state from Connecting => Connected. SkipAttach = False.
Ably: [Debug] 02:02:42.357 #16 Aborting timer 'Connecting state timer'
Ably: [Debug] 02:02:42.334 #31 Websocket data message received. Raw: ��action�channel�!ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=�channelSerial�e7db66cf50048766:54
Ably: [Debug] 02:02:42.357 #16 xx Connected: BeforeTransition
Ably: [Debug] 02:02:42.378 #16 Connection resumed!
Ably: [Debug] 02:02:42.379 #16 Connection notifying subscribers for state change `Connected`
==========Items connection: Connected, Thread:16 Serial:54
Ably: [Debug] 02:02:42.383 #16 xx Connected: Attaching state 
Ably: [Debug] 02:02:57.220 #23 Websocket data message received. Raw: ��actionException thrown: 'System.Runtime.InteropServices.ExternalException' in System.Drawing.dll
Ably: [Debug] 02:03:12.224 #21 Websocket data message received. Raw: ��actionException thrown: 'System.Runtime.InteropServices.ExternalException' in System.Drawing.dll
Ably: [Debug] 02:03:27.223 #29 Websocket data message received. Raw: ��actionAbly: [Debug] 02:03:42.220 #39 Websocket data message received. Raw: ��actionAbly: [Debug] 02:03:57.220 #37 Websocket data message received. Raw: ��action
Ably: [Debug] 02:04:12.239 #37 Websocket data message received. Raw: ��actionAbly: [Debug] 02:04:27.255 #12 Websocket data message received. Raw: ��actionException thrown: 'System.Runtime.InteropServices.ExternalException' in System.Drawing.dll
Ably: [Debug] 02:04:42.234 #30 Websocket data message received. Raw: ��actionAbly: [Debug] 02:04:57.231 #30 Websocket data message received. Raw: ��actionAbly: [Debug] 02:05:12.231 #30 Websocket data message received. Raw: ��action
Ably: [Debug] 02:05:27.235 #30 Websocket data message received. Raw: ��actionException thrown: 'System.Runtime.InteropServices.ExternalException' in System.Drawing.dll
Ably: [Debug] 02:05:42.333 #31 Websocket data message received. Raw: ��actionAbly: [Debug] 02:05:57.234 #18 Websocket data message received. Raw: ��actionAbly: [Debug] 02:06:12.243 #18 Websocket data message received. Raw: ��actionAbly: [Debug] 02:06:27.244 #30 Websocket data message received. Raw: ��action
Ably: [Debug] 02:06:42.243 #20 Websocket data message received. Raw: ��actionAbly: [Debug] 02:06:57.246 #30 Websocket data message received. Raw: ��actionAbly: [Debug] 02:07:12.320 #30 Websocket data message received. Raw: ��actionAbly: [Debug] 02:07:27.574 #37 Websocket data message received. Raw: ��action
Ably: [Debug] 02:07:42.728 #22 Websocket data message received. Raw: ��action
Ably: [Debug] 02:07:57.967 #22 Websocket data message received. Raw: ��actionAbly: [Debug] 02:08:13.064 #23 Websocket data message received. Raw: ��actionAbly: [Debug] 02:08:28.168 #32 Websocket data message received. Raw: ��actionException thrown: 'System.Runtime.InteropServices.ExternalException' in System.Drawing.dll
Ably: [Debug] 02:08:43.356 #30 Websocket data message received. Raw: ��actionAbly: [Debug] 02:08:58.466 #40 Websocket data message received. Raw: ��actionAbly: [Debug] 02:09:13.774 #40 Websocket data message received. Raw: ��actionAbly: [Debug] 02:09:28.773 #37 Websocket data message received. Raw: ��actionAbly: [Debug] 02:09:44.052 #37 Websocket data message received. Raw: ��actionAbly: [Debug] 02:09:59.096 #30 Websocket data message received. Raw: ��actionAbly: [Debug] 02:10:14.326 #40 Websocket data message received. Raw: ��action
Ably: [Debug] 02:10:29.361 #31 Websocket data message received. Raw: ��actionException thrown: 'System.IO.IOException' in mscorlib.dll
Ably: [Debug] 02:10:44.566 #23 Websocket data message received. Raw: ��actionException thrown: 'System.Runtime.InteropServices.ExternalException' in System.Drawing.dll
Ably: [Debug] 02:10:59.612 #15 Websocket data message received. Raw: ��actionAbly: [Debug] 02:11:14.838 #40 Websocket data message received. Raw: ��actionAbly: [Debug] 02:11:30.061 #40 Websocket data message received. Raw: ��action
Ably: [Debug] 02:11:45.117 #23 Websocket data message received. Raw: ��action
Ably: [Debug] 02:12:00.338 #14 Websocket data message received. Raw: ��action
Ably: [Debug] 02:12:15.370 #31 Websocket data message received. Raw: ��actionAbly: [Debug] 02:12:30.467 #31 Websocket data message received. Raw: ��actionAbly: [Debug] 02:12:45.650 #23 Websocket data message received. Raw: ��action
Ably: [Debug] 02:13:00.675 #15 Websocket data message received. Raw: ��action
Ably: [Debug] 02:13:16.091 #15 Websocket data message received. Raw: ��action
Ably: [Debug] 02:13:31.177 #32 Websocket data message received. Raw: ��action
Ably: [Debug] 02:13:41.399 #31 Websocket data message received. Raw: ��action�error��message�!Key/token status changed (expire)�code͜ΪstatusCode��
Ably: [Debug] 02:13:41.400 #16 xx Changing state from Connected => Disconnected. SkipAttach = False.
Ably: [Debug] 02:13:41.400 #31 Websocket data message received. Raw: ��action	�error��message�!Key/token status changed (expire)�code͜ΪstatusCode���timestamp�Ably: [Debug] 02:13:41.421 #16 xx Disconnected: BeforeTransition
Ably: [Debug] 02:13:41.422 #16 Connection notifying subscribers for state change `Disconnected`
==========Items connection: Disconnected, Thread:16 Serial:54
Ably: [Debug] 02:13:41.423 #16 xx Disconnected: Attaching state 
Ably: [Debug] 02:13:41.423 #16 Destroying transport
Ably: [Debug] 02:13:41.424 #16 Closing socket. Current socket is not null
Ably: [Debug] 02:13:41.424 #16 Setting up timer 'Disconnected state timer' to run action after 15 seconds. Autoreset: False
Ably: [Debug] 02:13:41.425 #16 xx Changing state from Disconnected => Connecting. SkipAttach = False.
Ably: [Debug] 02:13:41.425 #16 InState transition to 'Type: ConnectionConnectingState, State: Connecting'. Queuing tranport message until state updates
Ably: [Debug] 02:13:41.426 #16 Aborting timer 'Disconnected state timer'
Ably: [Debug] 02:13:41.426 #16 xx Connecting: BeforeTransition
Ably: [Debug] 02:13:41.427 #16 Connection notifying subscribers for state change `Connecting`
==========Items connection: Connecting, Thread:16 Serial:54
Ably: [Debug] 02:13:41.428 #16 xx Connecting: Attaching state 
Ably: [Debug] 02:13:41.428 #16 Creating transport
Ably: [Info] 02:13:41.429 #16 Sending GET request to https://mywebsite.com/ubft.php?hwid=nKWyBjoFxgd0lswgs%2BLWfVvR1Ho%3D&ttl=660&cb=85216
Ably: [Debug] 02:13:41.430 #16 Executing request: https://mywebsite.com/ubft.php?hwid=nKWyBjoFxgd0lswgs%2BLWfVvR1Ho%3D&ttl=660&cb=85216
Ably: [Debug] 02:13:43.294 #16 Connecting to web socket on url: wss://realtime.ably.io/?accessToken=rhSsEA.H1iMHAJ5ATMtOIg60yca8GBRnohJk3Orw-hSFAFITbcdQZCjQCmfah3wbupA5GKPo9mjxrZJM5ot0hWhHPFmYVQhLTa5_JbxcaV6WXOo04xJ8CxJGZWJfkX695sFAGA3O3SoFfVJpkcLLtSAj-dY9yitCs6mA8dz3tR5PPQBGTg-KyRB9UmmAxpMHjvonsKM1k1E5xT6yDXQU6-V93A7ixA&v=0.8&format=msgpack&echo=true&resume=e7dfb66c!IzbrpxbS544xdboL-83acee7dfb66c&connection_serial=54
Ably: [Debug] 02:13:43.296 #16 Connecting socket
Ably: [Debug] 02:13:43.296 #16 Setting up timer 'Connecting state timer' to run action after 10 seconds. Autoreset: False
Ably: [Debug] 02:13:43.297 #16 Proccessing queued message: { action=Error }
Ably: [Debug] 02:13:43.298 #16 Aborting timer 'Connecting state timer'
Ably: [Debug] 02:13:43.298 #16 xx Changing state from Connecting => Failed. SkipAttach = False.
Ably: [Debug] 02:13:43.299 #16 Aborting timer 'Connecting state timer'
Ably: [Debug] 02:13:43.300 #16 xx Failed: BeforeTransition
Ably: [Debug] 02:13:43.300 #16 Destroying transport
Ably: [Debug] 02:13:43.300 #16 Closing socket. Current socket is not null
Ably: [Debug] 02:13:43.301 #16 Connection notifying subscribers for state change `Failed`
Ably: [Debug] 02:13:43.301 #16 #ubfp:presence: Changing state to: 'Failed'. Error: Reason: Key/token status changed (expire); Code: 40142; HttpStatusCode: (401)Unauthorized
==========Presence channel:Failed ubfp:presence 
Ably: [Debug] 02:13:43.302 #16 #ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho=: Changing state to: 'Failed'. Error: Reason: Key/token status changed (expire); Code: 40142; HttpStatusCode: (401)Unauthorized
==========Item channel:Failed ubfi:nKWyBjoFxgd0lswgs+LWfVvR1Ho= 
==========Items connection: Failed, Thread:16 Serial:54
Key/token status changed (expire)
Ably: [Debug] 02:13:43.304 #16 xx Failed: Attaching state 
```

**Comment by marto83** [comment] 2016-06-13 14:53
I did a change to queue messages system message during state transitions because I was getting a Disconnected and an Error message when the token expired. So the issue is that I'm processing the Error message once the state's gone back to Connected which is not good. 
`Ably: [Debug] 02:13:43.297 #16 Proccessing queued message: { action=Error }`

I've been talking to @mattheworiordan about what to do when this happens. Hopeing to get it sorted today or tomorrow.

**Comment by mattheworiordan** [comment] 2016-06-13 16:14
Hi @lovetofail, apologies for this.  As @marto83 has quite rightly confirmed, this appears to be a protocol issue and not a dot net issue.  We'll get a fix out for this ASAP (today or tomorrow) or we'll implement a workaround in the short term.  Sorry for the inconvenience.

**Comment by mattheworiordan** [comment] 2016-06-14 11:57
@lovetofail we have rolled out a change to `sandbox` that has been tested with 3 client libs including .NET and it fixes this issue. We will test with our other libs now, and once ready, will roll this out to production.  I believe this issue will then go away.  That should be done art some point today.

**Comment by mattheworiordan** [comment] 2016-06-14 15:32
Hi @lovetofail.  I am told this fix has been pushed out to production now.  Would you mind confirming if the issue has gone for you or not?  I expect you can test this easily by reducing the TTL down for your tokens, see `ttl` within https://www.ably.io/documentation/realtime/types#token-params

**Closed** 2016-10-08 12:16 UTC
