### ISSUE TITLE
Crash in 1.1.6 on iOS & Android with Xamarin

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#346] opened 2019-06-04 22:07 UTC
Since updating to the 1.1.6 SDK we are seeing quite a few device crashes. 

See the stack trace for Xamarin:

```
CancellationToken.ThrowOperationCanceledException ()
CancellationToken.ThrowIfCancellationRequested ()
AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 ()
Task.InnerInvoke ()
Task.Execute ()
AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState)
AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken)
AblyHttpClient.InternalSendAsync (System.Net.Http.HttpRequestMessage message)
AblyHttpClient.Execute (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest (IO.Ably.AblyRequest request)```

```AblyRest.ExecuteRequest (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest[T] (IO.Ably.AblyRequest request)
AblyRest.TimeAsync ()
AblyAuth.SetServerTimeOffset ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.46(intptr,intptr)
```

iOS stack trace:

```
SUrlSessionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken)
AblyHttpClient.InternalSendAsync (System.Net.Http.HttpRequestMessage message)
AblyHttpClient.Execute (IO.Ably.AblyRequest request)
AblyHttpClient.Execute (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest[T] (IO.Ably.AblyRequest request)
AblyRest.TimeAsync ()
AblyAuth.SetServerTimeOffset ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

Note from dev:

> We do set QueryTime = true in the client config.
> And checked again and the Ably object creation definitely happens inside a try .. catch so odd that it should crash the app

**Comment by ndastur** [comment] 2019-06-04 22:08
Thank you @mattheworiordan

**Comment by mattheworiordan** [comment] 2019-06-05 07:54
@ndastur spoke with Jack this morning and he has a branch already looking at this issue, but won't be able to look at this properly until tomorrow I am afraid.

We'll be in touch soon hopefully with a fix we can share.  Apologies for the inconvenience.

**Comment by ndastur** [comment] 2019-06-06 11:37
Hi @mattheworiordan @withakay any news on this. We are seeing a real spike in crashes associated with this. Further info maybe in this slightly different crash report but seems to be related.
```
android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
libcore.io.Posix.android_getaddrinfo(Native Method)
libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
java.net.InetAddress.lookupHostByName(InetAddress.java:438)
java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
java.net.InetAddress.getAllByName(InetAddress.java:215)
com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
```

```
JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
HttpsURLConnectionInvoker.Connect ()
AndroidClientHandler+<>c__DisplayClass44_0.<ConnectAsync>b__0 ()
Task.InnerInvoke ()
Task.Execute ()
AndroidClientHandler.DoProcessRequest (System.Net.Http.HttpRequestMessage request, Java.Net.URL javaUrl, Java.Net.HttpURLConnection httpConnection, System.Threading.CancellationToken cancellationToken, Xamarin.Android.Net.AndroidClientHandler+RequestRedirectionState redirectState)
AndroidClientHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
HttpClient.SendAsyncWorker (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken)
AblyHttpClient.InternalSendAsync (System.Net.Http.HttpRequestMessage message)
AblyHttpClient.Execute (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest (IO.Ably.AblyRequest request)
java.net.UnknownHostException: Unable to resolve host "hospify-rest.ably.io": No address associated with hostname
java.net.InetAddress.lookupHostByName(InetAddress.java:457)
java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
java.net.InetAddress.getAllByName(InetAddress.java:215)
com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
libcore.io.Posix.android_getaddrinfo(Native Method)
libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
java.net.InetAddress.lookupHostByName(InetAddress.java:438)
```

```
AblyRest.ExecuteRequest (IO.Ably.AblyRequest request)
AblyRest.ExecuteRequest[T] (IO.Ably.AblyRequest request)
AblyRest.TimeAsync ()
AblyAuth.SetServerTimeOffset ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state)
QueueUserWorkItemCallback.WaitCallback_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
IThreadPoolWorkItem.ExecuteWorkItem ()
ThreadPoolWorkQueue.Dispatch ()
_ThreadPoolWaitCallback.PerformWaitCallback ()
```

**Comment by ndastur** [comment] 2019-06-06 11:41
As I have said my other big concern is about the way exceptions are being thrown. Has there been some fundamental change in the SDK with regards exceptions? We surround everything in try .. catch blocks. Crashing apps give a very poor user experience and so we generally show a prompt about network errors etc. For some reason, the new Ably .Net SDK is doing something that doesn't get caught by Xamarin side try..catch. My guess looking at the above is some sort of new threading model that throws exceptions that should not bubble up but be handled internally.

**Comment by mattheworiordan** [comment] 2019-06-06 12:15
> As I have said my other big concern is about the way exceptions are being thrown. Has there been some fundamental change in the SDK with regards exceptions?

No, in fact our implicit expectation was made explicit in 1.1, see https://github.com/ably/docs/blob/master/content/client-lib-development-guide/versions/features-1-0__1-1.diff#L62-L70

> Crashing apps give a very poor user experience and so we generally show a prompt about network errors etc.

I agree, it's very poor, and this should not happen.

**Comment by ndastur** [comment] 2019-06-06 12:39
Thanks @mattheworiordan.
@withakay any idea why the exceptions are bubbling up then and more importantly why they don't get caught by our Xamarin side try .. catch blocks?

**Comment by withakay** [comment] 2019-06-06 18:07
@ndastur 
The exception here is not caught by a try/catch because the work is being done by a thread from the ThreadPool.

Are you guys calling `Authorize` or `CreateTokenRequest` anywhere (as opposed to `Async` variants)?

**Comment by ndastur** [comment] 2019-06-06 18:12
@withakay no we are not. In fact we are not using Tokens at all. The reason for setting QueryTime = true is:
```
// We were getting token unauthorised errors
                        // Ably support say that token auth is used whenever a client ID is set, so need this
                        // https://support.ably.io/support/solutions/articles/3000068941-40101-timestamp-not-current
QueryTime = true
```

**Comment by mattheworiordan** [comment] 2019-06-06 18:18
@ndastur out of interest, that sound like you are relying on the client SDKs to generate tokens, as opposed to retrieve tokens from your servers.  Is that the case i.e. do clients have API keys?

**Comment by ndastur** [comment] 2019-06-06 18:41
@mattheworiordan we are still just using the API keys. No token generation at all. So yes clients have API keys.

**Comment by withakay** [comment] 2019-06-06 18:44
I think I have found the problem. A stupid error, that took me far too long to spot. See #347 for details

**Comment by ndastur** [comment] 2019-06-06 19:14
I'm hoping that fixes the bug reported on May 9th on our Slack channel. The reproduction steps for that one are to create an Ably object (rest or realtime) with QueryTime = true and then start the app with no network on the emulator.

**Comment by mattheworiordan** [comment] 2019-06-06 21:42
>  we are still just using the API keys. No token generation at all. So yes clients have API keys.

@ndastur OK, well the clients that have API keys may generate tokens under certain circumstances.  This has mostly changed in 1.1, so I suspect the fact that tokens are being generated is an indication that part of the 1,1 spec is not yet implemented in full,.  However, either way, I would urge you to reconsider using API keys in mobile apps: https://www.ably.io/documentation/core-features/authentication#selecting-auth

**Comment by withakay** [comment] 2019-06-07 13:54
1.1.8 has been released

**Comment by ndastur** [comment] 2019-06-07 20:15
Thank you @withakay . Will test but first success is that the crash in the debugger on startup with no network does not happen anymore

**Comment by withakay** [comment] 2019-06-24 20:58
@ndastur I am closing this, please reopen if there is still an issue.

**Closed by withakay** 2019-06-24 20:58 UTC
Labels: bug
