### ISSUE TITLE
Ably C# SDK version 1.2.14 failed to create instance of AblyRealTime 

### ISSUE THREAD

**Issue by bhaskarsoni-ai** [ably/ably-dotnet#1286] opened 2024-04-23 16:09 UTC
I am receiving following error when tried to use Ably NuGet package 1.2.14 with a .NET Framework 4.7.2 project.

Could not load file or assembly 'System.Threading.Channels, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Please see following image.

![image (2)](https://github.com/ably/ably-dotnet/assets/133196410/21d8834d-b7d5-4f20-b6bc-6e8cb18d7060)

After a discussion with Ably Support team, the recommendation was to add a nuget reference of System.Threading.Channels=4.6.0 
Even though we are getting following exception 

Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

![Error2](https://github.com/ably/ably-dotnet/assets/133196410/bc50ad36-6dbc-447b-8e97-2c1b85e07134)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4766) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment] 2024-04-23 16:43
If this still doesn't work. You can edit your `csproj` file for assembly binding as per https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by sacOO7** [comment] 2024-04-23 16:46
If issue still persists, it will be useful if you can post steps to reproduce above issue !

**Comment by bhaskarsoni-ai** [comment] 2024-04-24 03:36
@sacOO7 Steps to reproduce are very simple. You create a .net framework 4.7.2 project. Use ably nuget package and try to create the AblyRealTime instance. The exception is thrown.

We have tried this on multiple machines and it seems not to be a nuget package manager issue. We also using multiple nuget packages on same environment and we didn't face any such issues with other nuget packages.

Of course we can use this workaround  https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions. But we have other nuget packages which might using different versions of System.Threading.Tasks.Extensions (= 4.5.2) and i suspect it might start giving errors somewhere else.

**Comment by sacOO7** [comment] 2024-04-24 03:58
@bhaskarsoni-ai understood. We will take a look at it and will post an update once we are able to reproduce it from our side.

**Comment by sacOO7** [comment] 2024-04-24 04:31
Meanwhile you might like to take a look at https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by sacOO7** [comment] 2024-04-24 04:44
I strongly believe this is caused by other transitive dependencies in the project. So, using proper `binding-redirects` should be a viable fix.

**Comment by sacOO7** [comment] 2024-04-24 10:49
@bhaskarsoni-ai let me know if the fix is working for you. Just to be sure, you can try installing `ably-dotnet` in a plain netframework project where there are no transient dependency conflicts.

**Comment by sacOO7** [comment] 2024-04-25 01:18
Found one more useful link if you are interested -> https://davidsekar.com/asp-net/fixing-assembly-redirects-issue-quickly#!#google_vignette

**Comment by bhaskarsoni-ai** [comment] 2024-04-25 06:18
@sacOO7 Thanks for sharing the link and multiple soultions. Ours wrapper on Ably will be a standalone class library where Assembly redirect will difficult to use, as Assembly redirect can only be added inside App.Config. In a standalone library we don't have a app.config file.

**Comment by sacOO7** [comment] 2024-04-25 06:57
Okay, one final solution I can suggest is to add `reference DLL's` as a part of the project. You can follow https://stackoverflow.com/a/50716032. We are doing the same in case of `unity` -> https://github.com/ably/ably-dotnet/tree/main/unity/Assets/Ably/Plugins. You can see 3 different DLLs present 
1. [System.Threading.Channels.dll](https://github.com/ably/ably-dotnet/blob/main/unity/Assets/Ably/Plugins/System.Threading.Channels.dll)
2. [System.Threading.Tasks.Extensions.dll](https://github.com/ably/ably-dotnet/blob/main/unity/Assets/Ably/Plugins/System.Threading.Tasks.Extensions.dll)
3. [System.Runtime.CompilerServices.Unsafe.dll](https://github.com/ably/ably-dotnet/blob/main/unity/Assets/Ably/Plugins/System.Runtime.CompilerServices.Unsafe.dll)
Since, we are not installing them via from `Nuget`, ideally shouldn't generate conflicts. If there are conflict warnings, you should disable them. So, at runtime right version of assembly is resolved. 

Note - Being a netframework project, I am skeptical about not being able to add assembly redirects. I think you should be able to add it via some different configuration ( maybe editing .csproj or .sln file etc )

**Comment by bhaskarsoni-ai** [comment] 2024-04-25 08:32
@sacOO7  Please suggest what specific version of the dll I should be referring, suggested by you above

**Comment by sacOO7** [comment] 2024-04-25 08:37
You should visit https://www.nuget.org/packages/ably.io/1.2.15#dependencies-body-tab. under dependencies tab, you should be able to see the dependency with respective version. You need to download that dependency and use dll for the same. Also, you can click on the dependency to find out it's dependency, download it again till you finally download compiler.unsafe dll

**Comment by bhaskarsoni-ai** [comment] 2024-04-30 08:53
Hi @sacOO7 We are in the process of verifying the fix by using the workaround suggested. Will update once done.

**Comment by sacOO7** [comment] 2024-04-30 09:02
Found one more useful article you might like to take a look at https://learn.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies?source=recommendations. 
It does mention various methods to add support for assembly redirects.

**Comment by sacOO7** [comment] 2024-05-07 14:54
Hi @bhaskarsoni-ai do we have any update on the above?

**Comment by bhaskarsoni-ai** [comment] 2024-05-09 05:49
With using Assembly redirect we are not seeing any issues for now. Will keep you posted if something new observed @sacOO7

**Comment by sacOO7** [comment] 2024-05-09 06:03
Thanks for the update @bhaskarsoni-ai . 
I will be closing this issue for now. You can open a new issue in the future if needed !

**Closed by sacOO7** 2024-05-09 06:03 UTC
Labels: dependencies
