### ISSUE TITLE
Ably 1.1.8 - The type initializer for 'IO.Ably.Defaults' threw an exception.

### ISSUE THREAD

**Issue by jsinh** [ably/ably-dotnet#349] opened 2019-06-11 09:52 UTC
Throws exception when trying to initialize Ably Rest Client on C# SDK:

```
var signalClient = new IO.Ably.AblyRest(new IO.Ably.ClientOptions("ably-key"));
```

Exception: The type initializer for 'IO.Ably.Defaults' threw an exception.

**Comment by gtmadev** [comment] 2019-06-23 18:04
I dropped down to 1.1.6, which resolves issue for now.

**Comment by withakay** [comment] 2019-06-24 21:10
Could anyone suffering from this issue please provide more details as there is a test for this that passes

```
[Fact]
            public void WithKeyInOptions_InitialisesTheClient()
            {
                var client = new AblyRest(new ClientOptions(ValidKey));
                Assert.NotNull(client);
            }

**Comment by jsinh** [comment] 2019-06-25 02:27
Update: I tried to create a sample console - Full .NET framework - added Ably NuGet package and tried to trigger following two lines and it did not threw above exception:

```
try
{
    var signalClient = new AblyRest(new ClientOptions("ably-key"));
    signalClient.Channels.Get("some-channel").Publish(new Message { Data = JsonConvert.SerializeObject(new { Name = "Jsinh" }) });
}
catch (Exception exception)
{
    Console.WriteLine(exception);
    throw;
}
```

**Comment by jsinh** [comment] 2019-06-25 02:46
[AblyWebSignaling.zip](https://github.com/ably/ably-dotnet/files/3323330/AblyWebSignaling.zip)

This fails only when you try to add Ably to a web project and instantiate it.

In my case, I have created a brand new MVC / .NET Full framework project - updated all packages and added Ably to it. It throws an exception, please check attached zip for reference (above).

Also a screenshot of exception:
<img width="1133" alt="SS-000000" src="https://user-images.githubusercontent.com/1277539/60065457-86099280-9721-11e9-8c6d-c30d63550a01.png">

**Comment by gtmadev** [comment] 2019-06-25 05:12
See screenshot of debugger output and the code which causes the exception.

![Vr1enRu18Z](https://user-images.githubusercontent.com/30833539/60070855-d3e6c080-974a-11e9-8a23-f117601afc47.png)

**Comment by withakay** [comment] 2019-06-25 07:16
@jsinh Thanks for the repro!
@gtmadev Are you in a web context too?

**Comment by withakay** [comment] 2019-06-25 08:48
The problem is that we are registering for an event that is not available in a web context on .NET Framework. This issue has been be resolved in the v1.1.9-beta1 release, it would be great if you guys could try that version and feedback.
All going well we can push that out as a stable release shortly.
Thanks

**Comment by jsinh** [comment] 2019-06-25 09:22
@withakay - Confirmed upgrading to v1.1.9-beta1 package fixed the issue on console and web based app for using ably, thanks

**Comment by gtmadev** [comment] 2019-06-25 10:07
I can also confirm. v1.1.9-beta resolved the issue. Thx for the fast turnaround.

**Comment by gtmadev** [comment] 2019-06-25 10:08
> @jsinh Thanks for the repro!
> @gtmadev Are you in a web context too?

Yes. It's a .Net web API.

**Comment by withakay** [comment] 2019-07-03 14:56
Fixed in the next release, due today

**Closed by withakay** 2019-07-03 14:56 UTC
Labels: bug
