### ISSUE TITLE
Thread leak through disconnect/resume sequence

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-dotnet#313] opened 2019-04-04 18:23 UTC
This is a customer-reported problem:

> we are seeing a worker thread leak using the ably-dotnet client (Worker Thread    System.dll!System.Collections.Concurrent.BlockingCollection<System.Tuple<System.ArraySegment<byte>, System.Net.WebSockets.WebSocketMessageType>>.TryTakeWithNoTimeValidation).

> The number of this thread increased very quickly (per TTL cycle) when using 0.8.11 and causes thread exhaustion eventually. After upgrading to 1.1-beta, the leak occurs at a much lower rate, but still occurs when connection is lost resumed (automatically).

**Comment by bchenhs** [comment] 2019-04-04 18:30
This is observed when using the `AblyRealtime` API with the `AuthCallback` option.

Summary of our code:

[init]
_ablyRealtime = new AblyRealtime(_ablyClientOptions); //Environment, AuthCallback, ClientId
_ablyRealtime.Connection.On(param => ConnectionEventHandler(param));

[handler]
case ConnectionState.Connected: 
_ablyRtChannel = _ablyRealtime.Channels.Get(_ablyRtChannelName);
_ablyRtChannel.Subscribe(SubscriptionHandler);
_ablyRtChannel.Presence.EnterClientAsync(ABLY_CLIENT_UUID, null);

**Comment by withakay** [comment] 2019-04-05 05:08
@bchenhs 
Please provide details of your environment, as much detail as possible

- OS
- .NET Version 
- Additional context (ASP.Net, Xamarin etc.)

Could you additionally provide steps to reproduce?

Thanks.

**Comment by bchenhs** [comment] 2019-04-05 13:49
@withakay 
OS: Windows 10 (running in VMWare Fusion)
.NET: 4.7.2
Context: C# Windows Application targeting .NET 4.6

It is easiest to reproduce on 0.8.11:
1. (optional) set token refresh TTL to smaller values (e.g. 120 seconds)
2. Instantiate `AblyRealtime` with the AuthCallback option
3. On Connected, subscribe to channel and enter presence (and we made sure this is done only once and not on Connected event triggered by TTL cycle)
4. Watch the number of worker thread grow over time. 

On 1.1-beta, we didn't see the leak from TTL cycle (likely due to the improved inline token refresh). But the leak occurs when we simulate lost network connections (by disabling network, suspending VM, or put OS to sleep). I'm taking a wild guess but I think this leak is related to each re-connection attempt not killing the previous WebSocket worker.

**Comment by bchenhs** [comment] 2019-04-18 13:25
@withakay Just checking in to see if you need any help with more debug info. We looked forward to delivering Ably-provided notifications to our users on our Windows platform!

**Comment by mattheworiordan** [comment] 2019-04-18 18:06
Hey @bchenhs Jack is away right now in Sweden.  He will be back after Easter so I am sure will be in touch then.  Apologies for the delay with this.  I hope we get a fix out soon next week.

**Comment by withakay** [comment] 2019-04-25 11:54
Fixed by #318, a 1.1.1 release with these changes is imminent.

**Closed by withakay** 2019-04-25 11:54 UTC
Labels: bug

**Comment by mattheworiordan** [comment] 2019-04-25 11:58
@bchenhs once the 1.1.1 release is out, would you mind testing and confirming the issue is resolved for you?

**Comment by bchenhs** [comment] 2019-04-26 19:14
@mattheworiordan  Of course! I'll update here once I have data. Thanks, @withakay, for getting the fix out!

**Comment by bchenhs** [comment] 2019-04-26 20:17
I haven't been able to reproduce the thread leak issue with 1.1.1. It looks good to me!
