### ISSUE TITLE
The type initializer for 'IO.Ably.MsgPackHelper' threw an exception.  Method not found: '!!0[] System.Array.Empty()'.

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#87] opened 2016-11-11 20:44 UTC
Customer reporting the error when publishing with simple code like this in their QA/CI env:

```
string key = ConfigurationManager.AppSettings["IO.Ably"]; 
var client = new IO.Ably.AblyRest(key); 
var o = client.Channels.Get("Logger"); 
o.Publish("Debug", message);
```

Stack trace below:

```
The type initializer for 'IO.Ably.MsgPackHelper' threw 
an exception.; Code: 50000 
at IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext() in C:\projects\ably-dotn 
et\src\IO.Ably.Shared\AblyRest.cs:line 137 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot 
ification(Task task) 
at IO.Ably.AsyncHelper.RunSync(Func`1 func) in C:\projects\ably-dotnet\src\IO 
.Ably.Shared\SyncExtensions.cs:line 26 
at IO.Ably.Rest.RestChannel.Publish(String name, Object data, String clientId 
) in C:\projects\ably-dotnet\src\IO.Ably.Shared\Rest\Channel.cs:line 161 
at Warr.Services.DocumentProcessor.Logger.General(String message) 
at Warr.Services.DocumentProcessor.QueueManager.Process(Logger logger) 
The type initializer for 'IO.Ably.MsgPackHelper' threw an exception. 
at IO.Ably.MsgPackHelper.Serialise(Object obj) 
at IO.Ably.MessageEncoders.MessageHandler.GetMessagesRequestBody(IEnumerable` 
1 payloads, ChannelOptions options) in C:\projects\ably-dotnet\src\IO.Ably.Share 
d\MessageEncoders\MessageHandler.cs:line 131 
at IO.Ably.MessageEncoders.MessageHandler.GetRequestBody(AblyRequest request) 
in C:\projects\ably-dotnet\src\IO.Ably.Shared\MessageEncoders\MessageHandler.cs 
:line 122 
at IO.Ably.MessageEncoders.MessageHandler.SetRequestBody(AblyRequest request) 
in C:\projects\ably-dotnet\src\IO.Ably.Shared\MessageEncoders\MessageHandler.cs 
:line 83 
at IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext() in C:\projects\ably-dotn 
et\src\IO.Ably.Shared\AblyRest.cs:line 111 
Method not found: '!!0[] System.Array.Empty()'. 
at MsgPack.Serialization.ExtTypeCodeMapping.ValidateName(String name) 
at MsgPack.Serialization.ExtTypeCodeMapping.Add(String name, Byte typeCode) 
at MsgPack.Serialization.ExtTypeCodeMapping..ctor() 
at MsgPack.Serialization.SerializationContext..ctor(PackerCompatibilityOption 
s packerCompatibilityOptions) 
at IO.Ably.MsgPackHelper.GetContext() in C:\projects\ably-dotnet\src\IO.Ably. 
Shared\MsgPackHelper.cs:line 21 
at IO.Ably.MsgPackHelper..cctor() in C:\projects\ably-dotnet\src\IO.Ably.Shar 
ed\MsgPackHelper.cs:line 15 
Unexpected Error Reason: Unexpected error :The type initializer for 'IO.Ably.Msg 
PackHelper' threw an exception.; Code: 50000 
Reason: Unexpected error :The type initializer for 'IO.Ably.MsgPackHelper' threw 
an exception.; Code: 50000 
at IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext() in C:\projects\ably-dotn 
et\src\IO.Ably.Shared\AblyRest.cs:line 137
```

**Comment by marto83** [comment] 2016-11-11 22:15
Hi Matt. Which version of the library is this from 0.8.3 or 0.8.4-rc1

**Comment by mattheworiordan** [comment] 2016-11-12 15:22
Unlikely to be 0.8.4-rc1, I will check, but assume 0.8.3 unless you hear otherwise

**Comment by marto83** [comment] 2016-11-12 16:03
0.8.4 will pass the version when making a connection. The issue is cause by
the way nuget makes dependency upgrades. They will need to downgrade
MsgPack to version 0.6.8 or upgrade the ably library to the next version.

**Comment by mattheworiordan** [comment] 2016-11-12 17:34
@marto83 the customer is already using 0.8.4-rc1

**Comment by marto83** [comment] 2016-11-12 17:57
I read the error message again. It seems to be something specific to the
received message.

Can you ask them for a debug log output? This now can be done using the
ClientOptions. They switch to 'usebinaryprotocol' = false for the time
being until I figure out what's causing it.

**Comment by mattheworiordan** [comment] 2016-11-12 17:59
Asked customer to monitor this issue as it's getting a bit silly acting as a conduit!

**Comment by gwestwater** [comment] 2016-11-12 18:49
How do I enabled the debug log output specific to what you are looking for?

Or are you just looking for a stack trace?

**Comment by mattheworiordan** [comment] 2016-11-12 19:02
> How do I enabled the debug log output specific to what you are looking for?

You can set the static logger log level to verbose at https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Logger.cs#L42.

Once you do that, it will perform verbose logging everywhere.  If you could perhaps email that log to support@ably.io as it may contain sensitive info then we can review in detail.

Thanks.

**Comment by gwestwater** [comment] 2016-11-12 19:36
I will do that at my next possible opportunity thank you

**Comment by mattheworiordan** [comment] 2016-11-16 11:11
Hi @gwestwater, any chance you had time to do that and send us the log?

**Comment by marto83** [comment] 2017-06-18 22:41
@gwestwater I'm going to close this ticket. If it is still an issue please feel free to reopen it.

**Closed by marto83** 2017-06-18 22:41 UTC
Labels: bug
