### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by NVentimiglia** [ably/ably-dotnet#109] opened 2017-06-21 02:37 UTC
Vs 0.8.4.4

Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
SuperSocket.ClientEngine.ConnectAsyncExtension.SocketConnectCompleted(object sender, SocketAsyncEventArgs e)<2b3384da5fba458d95aaf3e5bd2b26a7>:0
SuperSocket.ClientEngine.ConnectAsyncExtension.OnGetHostAddresses(IAsyncResult result)<2b3384da5fba458d95aaf3e5bd2b26a7>:0
System.Runtime.Remoting.Messaging.AsyncResult.Invoke(AsyncResult)(wrapper managed-to-native)
System.Runtime.Remoting.Messaging.AsyncResult.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()<b372b86075aa499fb19b0e7f203d3426>:0
System.Threading.ThreadPoolWorkQueue.Dispatch()<b372b86075aa499fb19b0e7f203d3426>:0
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()<b372b86075aa499fb19b0e7f203d3426>:0

**Comment by mattheworiordan** [comment] 2017-06-21 09:42
Do you have any information on what may have led to this issue?
See https://support.ably.io/solution/articles/3000063743-guide-information-we-need-to-help-you-diagnose-problems for common information that will help us more quickly diagnose and fix issues.

**Comment by marto83** [comment] 2017-06-21 10:20
@mattheworiordan this is the third issue of this sort. It happens deep within the WebSocket4Net library but  it doesn't happen often. 

@NVentimiglia kerryjiang suggested we upgrade to the latest version of beta version of WebSocket4Net. Our other option is to use the 0.8.5 beta version of ably which uses the MS implementation. 

Do you have any more insight into when the issue is happening? Have you managed to recreate it in a dev environment? Could it be related to the phone losing reception?

Which of the above two options do you prefer? I'll be happy to create a version of ably with the latest beta of WebSocket4Net?

**Comment by mattheworiordan** [comment] 2017-06-21 10:26
@marto83 does 0.8.6 use the MS implementation?

**Comment by marto83** [comment] 2017-06-21 10:33
0.8.4.* uses WebSocket4Net
0.8.5* uses System.Net.WebSockets.Client

**Comment by mattheworiordan** [comment] 2017-06-21 10:42
Thanks @marto83. So @NVentimiglia can you try the latest version?

**Comment by caseyniemann** [comment] 2017-06-23 17:36
@mattheworiordan we have 8.5 in dev.  We are testing backward compat if we have one client on 8.4 and one on 8.5...should we expect issues?  @NVentimiglia

**Comment by marto83** [comment] 2017-06-23 17:41
@caseyniemann There will be no compatibility issues between the two versions.

The protocol is the same. The differences between the versions are:
1. 8.5 supports .net standard 1.3 so I had to swap a few internal apis
2. Swapped the web socket protocol.

8.5 is not signed yet. Let me know if you require a signed assembly.

**Comment by caseyniemann** [comment] 2017-06-23 18:10
We updated 8.5 is updated in Dev using Nuget...testing

**Comment by marto83** [comment] 2017-06-23 20:58
Thanks for letting me know. Keep us updated how testing goes and whether to experience any issues.

**Comment by marto83** [comment] 2017-08-13 23:15
Fixed in 0.8.5 beta 18

**Closed by marto83** 2017-08-13 23:15 UTC
Labels: bug
