### ISSUE TITLE
There is already one outstanding 'SendAsync' call for this WebSocket instance 

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#101] opened 2017-05-03 11:02 UTC
Got this exception using this commit f84f5b5bfdc77df234f376ae6502290ac8487851
`There is already one outstanding 'SendAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.`
 ```
  at System.Net.WebSockets.WebSocketBase.<SendAsyncCore>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at IO.Ably.Transport.MsWebSocketConnection.<SendData>d__17.MoveNext() in D:\Temp\Push\ably-dotnet\src\IO.Ably.Shared\Transport\MsWebSocketConnection.cs:line 88
```

**Comment by mattheworiordan** [comment] 2017-05-03 11:17
Thanks for reporting, we'll investigate

**Comment by marto83** [comment] 2017-05-03 22:47
Thanks @lovetofail I had a look and know how to fix it. I'll push an update in the next couple of days.

**Comment by marto83** [comment] 2017-05-10 22:15
Hi @lovetofail. I've updated the code and added a queue to make sure only one SendAsync is happening. Since the change I haven't managed to reproduce the bug. 

Please use `0.8.5-beta6` package from nuget. Let me know if you have any other issues.

**Comment by marto83** [comment] 2017-06-13 22:52
@lovetofail have you had the issue again. I'm going to close the ticket. Feel free to reopen it if you see the same issue again.

**Comment by DaTester** [comment] 2018-08-21 14:49
We have been getting the message below reported in our apps on a regular bases (Xamarin apps  - iOS, android and UWP.  using ably .net 0.8.11) . 
".PublishAsync timeout expired. Message was not confirmed by the server " 
We cannot find a way to easily repeat the issue, but have attached log file which shows the error.
We done testing on windows 10 Pro machine (ver 1803 64bit) using ably .net 0.8.11

[ABlyLog.txt](https://github.com/ably/ably-dotnet/files/2306769/ABlyLog.txt)

**Comment by withakay** [comment] 2018-08-21 19:47
@DaTester are you only seeing this since updating to 0.8.11?

**Comment by DaTester** [comment] 2018-08-24 11:26
just to update you further on this issue:  In our app we are using  1 connection with 3 channels.
We will test further to find out when the issue occurs.

**Comment by DaTester** [comment] 2018-10-17 12:01
Hi @withakay ,  you can close this issue.  We found the issue was caused by sending a message on the sleep event,  it seems to have caused  some sort of race hazard in our code.  
We do have another issue - System.NullReferenceException - Object reference not set to an instance of an object. which occurs randomly when device is woken from sleep.  but i can't reproduce on demand.  I'll update you when i get more info in this.

**Comment by withakay** [comment] 2018-10-17 13:37
@DaTester Thanks for the heads up.
Please see https://github.com/ably/ably-dotnet/issues/264, it might relate to your null reference exception. Drop a comment over there if you think it does

**Closed** 2018-10-17 13:57 UTC
